name: Security
on: 
  push:
    branches: [ main, develop ]
  pull_request:
    type: [ opened, reopened ]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true

      - name: Run brakeman
        run: bundle exec brakeman

    timeout-minutes: 3
