name: Ruby

on: [push, pull_request]

jobs:
  rspec:
    name: Rspec
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        ports:
          - 3306:3306
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.2.2"
    - name: Bundler and gem install
      run: |
        gem install bundler
        bundle install --path vendor/bundle --quiet --jobs 4 --retry 3
    - name: Database create and migrate
      run: |
        cp config/database.yml.ci config/database.yml
        bundle exec rails db:create RAILS_ENV=test
        bundle exec rails db:migrate RAILS_ENV=test
    - name: Test with Rspec
      run: |
        bundle exec rspec
