# ref https://github.com/everyleaf/el-training/blob/master/github_actions/.github/workflows/lint.yml
name: Lint
on: 
  push:
    branches: [ main, develop ]
  pull_request:
    type: [ opened, reopened ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true
      - name: Run lint
        run: bundle exec rubocop
    timeout-minutes: 3
